### ISSUE TITLE
What is New Pathways?

### ISSUE THREAD

**Issue by glitchedmob** [Open-SGF/gooddads#10]

**Comment by jugglingdev** [comment]
Federal mandate for healthy marriages and responsible fatherhood
GoodDads is the contract holder for Region 5 in Missouri 
New Pathways for GoodDads is the name of the program in the office (overarching umbrella)
Participants get several things as a benefit and also have requirements for completion
GoodDads 2.0 and Within My Reach are healthy relationships classes
Star students of New Pathways program = have a job, contribute to kids' wellbeing, complete both classes (access to program for 18 months)

Another program is GoodDads Strong Schools
