### ISSUE TITLE
What are the different statuses for the participants?

### ISSUE THREAD

**Issue by glitchedmob** [Open-SGF/gooddads#12]
e.g. pending, approved, active, alumni

**Comment by jugglingdev** [comment]
- Inactive
- Active:
-- Enrolled in 1st class
-- Completed 1st class
-- Enrolled in 2nd class
-- Completed 2nd class

Waitlisted

Status (approved, etc.) 
Class Status (see above)

status for someone who has completed classes but is still active in program - access to resources
