### ISSUE TITLE
High level, what does your organization need? What solution would be the most helpful

### ISSUE THREAD

**Issue by glitchedmob** [Open-SGF/gooddads#13]

**Comment by jugglingdev** [comment]
A way to streamline the enrollment process in a way that makes enrollment feel less cumbersome or intimidating
An important tool for class engagement/practical application of class concepts and GoodDads being able to glean information from its ongoing classes for reporting strategies and show that the system is working and there's measurement improvement from the time someone enrolls in the class to the time they graduate
